import random
import pyodbc

# ──────────────────────────────────────────────
# HOTEL BOOKING operations
# ──────────────────────────────────────────────
def hotel_select_guests(cursor):
    cursor.execute("SELECT TOP 5 guest_id, first_name, last_name, email FROM guests ORDER BY NEWID()")
    return cursor.fetchall()

def hotel_select_reservations(cursor):
    cursor.execute("SELECT TOP 5 reservation_id, status, check_in, check_out FROM reservations ORDER BY NEWID()")
    return cursor.fetchall()

def hotel_select_rooms(cursor):
    cursor.execute("SELECT TOP 5 room_id, room_number, status FROM rooms ORDER BY NEWID()")
    return cursor.fetchall()

def hotel_insert_reservation(cursor):
    cursor.execute("SELECT TOP 1 guest_id FROM guests ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        gid = row[0]
        cursor.execute("""
            INSERT INTO reservations (guest_id, check_in, check_out, status, num_guests, source)
            VALUES (?, DATEADD(day, ?, GETDATE()), DATEADD(day, ?, GETDATE()), 'confirmed', ?, 'load_test')
        """, gid, random.randint(1, 30), random.randint(31, 60), random.randint(1, 4))
        return cursor.rowcount
    return 0

def hotel_update_reservation_status(cursor):
    cursor.execute("SELECT TOP 1 reservation_id FROM reservations WHERE status = 'confirmed' ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        rid = row[0]
        statuses = ['checked_in', 'checked_out', 'cancelled']
        cursor.execute("UPDATE reservations SET status = ? WHERE reservation_id = ?",
                       random.choice(statuses), rid)
        return cursor.rowcount
    return 0

def hotel_delete_cancellation(cursor):
    cursor.execute("SELECT TOP 1 cancellation_id FROM cancellations ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        cursor.execute("DELETE FROM cancellations WHERE cancellation_id = ?", row[0])
        return cursor.rowcount
    return 0

HOTEL_OPERATIONS = [
    ("SELECT guests", hotel_select_guests),
    ("SELECT reservations", hotel_select_reservations),
    ("SELECT rooms", hotel_select_rooms),
    ("INSERT reservation", hotel_insert_reservation),
    ("UPDATE reservation", hotel_update_reservation_status),
    ("DELETE cancellation", hotel_delete_cancellation),
]

# ──────────────────────────────────────────────
# E-COMMERCE operations
# ──────────────────────────────────────────────
def ecom_select_products(cursor):
    cursor.execute("SELECT TOP 5 product_id, name, unit_price FROM products ORDER BY NEWID()")
    return cursor.fetchall()

def ecom_select_orders(cursor):
    cursor.execute("SELECT TOP 5 order_id, customer_id, status, total_amount FROM orders ORDER BY NEWID()")
    return cursor.fetchall()

def ecom_select_customers(cursor):
    cursor.execute("SELECT TOP 5 customer_id, first_name, last_name, email FROM customers ORDER BY NEWID()")
    return cursor.fetchall()

def ecom_insert_product(cursor):
    sku = f"SKU-LOAD-{random.randint(100000, 999999)}"
    cursor.execute("""
        INSERT INTO products (sku, name, description, unit_price, cost_price, is_active)
        VALUES (?, ?, ?, ?, ?, 1)
    """, sku, f"Load Test Product {random.randint(1, 9999)}",
          "Generated by load test", round(random.uniform(10, 500), 2), round(random.uniform(5, 250), 2))
    return cursor.rowcount

def ecom_insert_order(cursor):
    cursor.execute("SELECT TOP 1 customer_id FROM customers ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        cid = row[0]
        onum = f"ORD-LOAD-{random.randint(10000000, 99999999)}"
        cursor.execute("""
            INSERT INTO orders (customer_id, total_amount, shipping_amount, tax_amount, status, order_number)
            VALUES (?, ?, ?, ?, 'pending', ?)
        """, cid, round(random.uniform(20, 500), 2), round(random.uniform(5, 30), 2),
              round(random.uniform(2, 40), 2), onum)
        return cursor.rowcount
    return 0

def ecom_update_order_status(cursor):
    cursor.execute("SELECT TOP 1 order_id FROM orders WHERE status = 'pending' ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        oid = row[0]
        statuses = ['processing', 'shipped', 'delivered']
        cursor.execute("UPDATE orders SET status = ? WHERE order_id = ?", random.choice(statuses), oid)
        return cursor.rowcount
    return 0

ECOM_OPERATIONS = [
    ("SELECT products", ecom_select_products),
    ("SELECT orders", ecom_select_orders),
    ("SELECT customers", ecom_select_customers),
    ("INSERT product", ecom_insert_product),
    ("INSERT order", ecom_insert_order),
    ("UPDATE order status", ecom_update_order_status),
]

# ──────────────────────────────────────────────
# ERP SYSTEM operations
# ──────────────────────────────────────────────
def erp_select_employees(cursor):
    cursor.execute("SELECT TOP 5 employee_id, first_name, last_name, email FROM employees ORDER BY NEWID()")
    return cursor.fetchall()

def erp_select_projects(cursor):
    cursor.execute("SELECT TOP 5 project_id, name, status FROM projects ORDER BY NEWID()")
    return cursor.fetchall()

def erp_select_journal_entries(cursor):
    cursor.execute("SELECT TOP 5 je_id, entry_number, entry_date FROM journal_entries ORDER BY NEWID()")
    return cursor.fetchall()

def erp_insert_employee(cursor):
    cursor.execute("SELECT TOP 1 company_id FROM companies ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        co_id = row[0]
        cursor.execute("SELECT TOP 1 dept_id FROM departments WHERE company_id = ? ORDER BY NEWID()", co_id)
        dept = cursor.fetchone()
        if dept:
            did = dept[0]
            em = f"load.emp.{random.randint(10000, 99999)}@erp.com"
            cursor.execute("""
                INSERT INTO employees (company_id, dept_id, first_name, last_name, email, salary, status)
                VALUES (?, ?, ?, ?, ?, ?, 'active')
            """, co_id, did, f"LoadFirst{random.randint(1, 999)}",
                  f"LoadLast{random.randint(1, 999)}", em, round(random.uniform(30000, 150000), 2))
            return cursor.rowcount
    return 0

def erp_insert_project(cursor):
    cursor.execute("SELECT TOP 1 company_id FROM companies ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        co_id = row[0]
        pcode = f"PRJ-LOAD-{random.randint(1000, 9999)}"
        cursor.execute("""
            INSERT INTO projects (company_id, name, code, description, start_date, status)
            VALUES (?, ?, ?, ?, GETDATE(), 'planning')
        """, co_id, f"Load Project {random.randint(1, 9999)}", pcode,
              "Generated by load test")
        return cursor.rowcount
    return 0

def erp_update_employee_salary(cursor):
    cursor.execute("SELECT TOP 1 employee_id FROM employees ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        eid = row[0]
        cursor.execute("UPDATE employees SET salary = ? WHERE employee_id = ?",
                       round(random.uniform(35000, 160000), 2), eid)
        return cursor.rowcount
    return 0

ERP_OPERATIONS = [
    ("SELECT employees", erp_select_employees),
    ("SELECT projects", erp_select_projects),
    ("SELECT journal entries", erp_select_journal_entries),
    ("INSERT employee", erp_insert_employee),
    ("INSERT project", erp_insert_project),
    ("UPDATE salary", erp_update_employee_salary),
]

# ──────────────────────────────────────────────
# HRM TOOL operations
# ──────────────────────────────────────────────
def hrm_select_employees(cursor):
    cursor.execute("SELECT TOP 5 employee_id, employee_code, first_name, last_name FROM employees_hrm ORDER BY NEWID()")
    return cursor.fetchall()

def hrm_select_leave(cursor):
    cursor.execute("SELECT TOP 5 leave_id, status, start_date, end_date FROM leave_applications_hrm ORDER BY NEWID()")
    return cursor.fetchall()

def hrm_insert_training(cursor):
    cursor.execute("""
        INSERT INTO training_programs (org_id, program_name, description, trainer, duration_hours, mode, is_active)
        SELECT TOP 1 org_id, ?, ?, ?, ?, 'online', 1 FROM organizations ORDER BY NEWID()
    """, f"Load Training {random.randint(1, 999)}",
          "Generated by load test", f"Trainer {random.randint(1, 50)}", random.randint(4, 40))
    return cursor.rowcount

def hrm_insert_leave_application(cursor):
    cursor.execute("SELECT TOP 1 employee_id FROM employees_hrm ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        eid = row[0]
        cursor.execute("SELECT TOP 1 policy_id FROM leave_policies ORDER BY NEWID()")
        pol = cursor.fetchone()
        if pol:
            pid = pol[0]
            ndays = random.randint(1, 5)
            cursor.execute("""
                INSERT INTO leave_applications_hrm (employee_id, policy_id, start_date, end_date, total_days, reason, status)
                VALUES (?, ?, CAST(GETDATE() AS DATE), DATEADD(day, ?, CAST(GETDATE() AS DATE)), ?, 'Load test leave', 'pending')
            """, eid, pid, ndays, ndays)
            return cursor.rowcount
    return 0

HRM_OPERATIONS = [
    ("SELECT employees_hrm", hrm_select_employees),
    ("SELECT leave", hrm_select_leave),
    ("INSERT training", hrm_insert_training),
    ("INSERT leave", hrm_insert_leave_application),
]

# ──────────────────────────────────────────────
# DEPARTMENT STORE operations
# ──────────────────────────────────────────────
def store_select_products(cursor):
    cursor.execute("SELECT TOP 5 product_id, sku, name, unit_price FROM products_store ORDER BY NEWID()")
    return cursor.fetchall()

def store_select_sales(cursor):
    cursor.execute("SELECT TOP 5 transaction_id, total_amount, payment_method FROM sales_transactions ORDER BY NEWID()")
    return cursor.fetchall()

def store_select_inventory(cursor):
    cursor.execute("SELECT TOP 5 inventory_id, quantity, location_code FROM inventory_store ORDER BY NEWID()")
    return cursor.fetchall()

def store_insert_sale(cursor):
    cursor.execute("SELECT TOP 1 store_id FROM stores ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        sid = row[0]
        cursor.execute("SELECT TOP 1 employee_id FROM employees_store ORDER BY NEWID()")
        emp = cursor.fetchone()
        eid = emp[0] if emp else 1
        rcp = f"RCPT-LOAD-{random.randint(10000000, 99999999)}"
        cursor.execute("""
            INSERT INTO sales_transactions (store_id, employee_id, subtotal, tax_amount, total_amount, payment_method, receipt_number, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, 'completed')
        """, sid, eid, round(random.uniform(10, 500), 2), round(random.uniform(1, 40), 2),
              round(random.uniform(11, 540), 2),
              random.choice(['cash', 'credit_card', 'debit_card', 'mobile_pay']), rcp)
        return cursor.rowcount
    return 0

def store_insert_promotion(cursor):
    cursor.execute("SELECT TOP 1 store_id FROM stores ORDER BY NEWID()")
    row = cursor.fetchone()
    if row:
        sid = row[0]
        cursor.execute("""
            INSERT INTO promotions (store_id, promotion_name, description, discount_type, discount_value, min_purchase, start_date, end_date, is_active)
            VALUES (?, ?, ?, 'percent', ?, ?, GETDATE(), DATEADD(day, 30, GETDATE()), 1)
        """, sid, f"Load Promo {random.randint(1, 999)}",
              "Generated by load test", round(random.uniform(5, 50), 2), round(random.uniform(10, 100), 2))
        return cursor.rowcount
    return 0

STORE_OPERATIONS = [
    ("SELECT products_store", store_select_products),
    ("SELECT sales", store_select_sales),
    ("SELECT inventory", store_select_inventory),
    ("INSERT sale", store_insert_sale),
    ("INSERT promotion", store_insert_promotion),
]

# ──────────────────────────────────────────────
# Operation registry
# ──────────────────────────────────────────────
DATABASE_OPERATIONS = {
    "hotel_booking": HOTEL_OPERATIONS,
    "e_commerce": ECOM_OPERATIONS,
    "erp_system": ERP_OPERATIONS,
    "hrm_tool": HRM_OPERATIONS,
    "department_store": STORE_OPERATIONS,
}
